# This file was automatically generated by kynetix-webapp (https://github.com/PytLab/kynetix-webapp).
# Version 0.1.0
# Date: Tue Jul  4 19:59:08 2017 
#
# Do not make changes to this file unless you know what you are doing

# Gas pressure.
species_definitions = {}
species_definitions['CO_g'] = {'pressure': 1.32e-07}
species_definitions['O2_g'] = {'pressure': 5.26e-07}
species_definitions['CO2_g'] = {'pressure': 1.32e-07}

# Site info.
species_definitions['*_s'] = {'type': 'site', 'total': 1.0}

#Temperature.
temperature = 500.0  # K

parser = 'RelativeEnergyParser'
solver = 'SteadyStateSolver'
corrector = 'ThermodynamicCorrector'
plotter = 'EnergyProfilePlotter'

unitcell_area = 9e-20
active_ratio = 0.4444444444444444

rate_algo = 'CT'
rootfinding = 'MDNewton'
tolerance = 1.000000e-50
max_rootfinding_iterations = 100
