# This file was automatically generated by KinLab (https://github.com/PytLab/KinLab).
# Version 0.1.0
# Date: Fri Jul 28 23:56:34 2017 
#
# Do not make changes to this file unless you know what you are doing

Ga, dG = [], []

# CO_g + *_s -> CO_s
Ga.append(0.0)
dG.append(-2.09)

# O2_g + 2*_s -> 2O_s
Ga.append(0.07)
dG.append(-2.39)

# CO_s + O_s <-> CO-O_2s -> CO2_g + 2*_s
Ga.append(0.39)
dG.append(-0.46)
