# This file was automatically generated by KinLab (https://github.com/PytLab/KinLab).
# Version 0.1.0
# Date: Fri Jul 28 23:56:34 2017 
#
# Do not make changes to this file unless you know what you are doing

rxn_expressions = [
    'CO_g + *_s -> CO_s',
    'O2_g + 2*_s -> 2O_s',
    'CO_s + O_s <-> CO-O_2s -> CO2_g + 2*_s',
]

