#!/usr/bin/env python
# -*- coding: utf-8 -*-

''' Blueprint
'''

import time

from flask import Blueprint

main = Blueprint('main', __name__)

__version__ = '0.1.0'

FILE_HEADER = (
    '# This file was automatically generated by KinLab' +
    ' (https://github.com/PytLab/KinLab).\n' +
    '# Version %s\n# Date: %s \n#\n' +
    '# Do not make changes to this file ' +
    'unless you know what you are doing\n\n') % (__version__, time.asctime())

from .files import *
from .model import *
from .job import *
from .report import *

